### ISSUE TITLE
Any examples for SSL/TLS auth?

### ISSUE THREAD

**Issue by sprajagopal** [python-caldav/caldav#144]
Hi,
Could you add a few examples on how to use the `auth` variable in DAVClient? Particularly for SSL/TLS auth.

**Comment by tobixen** [comment]
For the ordinary cases it is sufficient to just pass a https URL.  As far as I remember, someone added the auth parameter because they needed special code for authenticating a self-signed certificate.  This is a pretty rare corner case (for self-signed certificates it's also possible to pass `ssl_verify_cert=False`).  If one really needs it, I suggest checking out the documentation at https://docs.python-requests.org/en/master/user/advanced/#custom-authentication

I don't have capacity to add any example code for this, but I would happily accept a pull request :-)

**Comment by sprajagopal** [comment]
Ok I found the issue I had. It was the same as #50.
