### ISSUE TITLE
How to filter events by property

### ISSUE THREAD

**Issue by Jorilx** [python-caldav/caldav#16]
I'm sorry, what is the recommended way to filter/search a calendar by a property? For example, "fetch me all the events with 'HOLIDAY' as summary"

**Comment by tobixen** [comment]
With the current version, the simplest way is probably to do a date_search and then filter on the client side.

I should consider to fix better functionality for date_search and todo-search with filtering,

**Comment by tobixen** [comment]
I'm considering to add more parameters to date_search and include a fix in 0.7.  At the other hand ...

* The caldav query language is quite arcane
* ... so arcane that quite some caldav server programmers fail to get it right
* the caldav query langauge is also somewhat restricted
* I did some research into server-side search when implementing task lists in calendar-cli - but ended up with fetching all tasks and doing sorting and selecting on the client side.

**Comment by tobixen** [comment]
A proper fix will be postponed until 0.8 or 1.0.  However, I have moved logic from the date_search-method into a build_date_search_query method and a search-method, so that it should be theoretically possible to either modify the query or hand-feed the search-method with some query XML.

Remaining work on this issue:

* Play with it, see it it's possible to make some queries in XML (string) and get out search results.  Fix some test code for this.
* Play with it, see if it's possible to build same queries using the classes under caldav.elements.cdav.  Fix test code.
* See if it's practically possible to create queries by modifying the return results from the build_date_search_query-method, and create test code for this
* Think out if there are more parameters that are suitable to pass, and other simplified search methods that ought to be added, and ... of course, add test code for it.

**Comment by tobixen** [comment]
I'm working no a new method `calendar.search()` in the master branch

**Comment by tobixen** [comment]
The list of properties that it should be possible to filter is not complete, and I'm also intending to do quite some work with client side filtering to iron over various incompatibilities with the different calendar servers.  Anyway, I close this issue and will eventually open (an) other issue(s) for that later on.
