### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by brutus2nd** [python-caldav/caldav#173]
Hi,
many thanks for providing the code for caldav client.
I tried to use the basic_usage_examples.py , but am facing an issue I could not solve.
I have a freedombox running radicale caldav server and I would like to get access to it via simple caldav client from Python script.
Do you have a recommendation on how to solve this issue:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
it is followed by other errors:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool
and:
requests.exceptions.SSLError: HTTPSConnectionPool

Thanks for your help!

**Comment by tobixen** [comment]
Try this:

    client = caldav.DAVClient(url=caldav_url, username=username, password=password, ssl_verify_cert=False)

`ssl_verify_cert` can also be a path name to a CA-bundle

**Comment by brutus2nd** [comment]
Great, thanks a lot for fast reply!!
It worked out. Sure there are some security warnings, but nothing of importance in my case.
To use the ssl_verify_cert: this should be the one from the server? would the path work? Probably I did not understand correctly. Can you shortly explain? Thanks again

**Comment by tobixen** [comment]
If you have some knowledge of PKI and certificate handling and have special security requirements (privately signed certs that should be verified), then ssl_verify_cert should point to your private CA certificate.  In your case, you'd probably want to leave it as `False` :-)

Well, since the certificate is actually "self-signed", then maybe ssl_verify_cert can be set to the path name of the certificate itself.  I don't know.  I'm no expert on PKI and certificate handling myself :-)

Replacing the self-signed cert with a LetsEncrypt-cert should also be relatively easy to do.
