### ISSUE TITLE
String conversion leads to exception when using proxy and basic auth

### ISSUE THREAD

**Issue by neelusR** [python-caldav/caldav#179]
I am trying davclient.py with a proxy and a NextCloud server. Because the server returns a 401 on the first try, another call is done. However because on line 513 "url = str(url)", the URL is converted to a string, the proxy setting on line 506 runs into an exception

**Comment by tobixen** [comment]
Stupid question, I'll just open the editor and check :-)

**Comment by neelusR** [comment]
At the moment I having a problem commiting to github from my laptop. I have a local fix. Let me check if I can fix this week.

**Comment by tobixen** [comment]
There is also the good old style way of sending a patch :-)

**Comment by tobixen** [comment]
It's a bit strange, because there is a `testProxy` in `tests/test_caldav.py`, and it passes on all servers I've tested.

v0.9 is way overdue, and I'm probably ready to release it tomorrow morning, but I don't have capacity to check more up on this proxy issue.  If you have some patch ready or almost-ready, then let me know, and I'll try to shoehorn it in before the release.

**Comment by tobixen** [comment]
I have managed to reproduce the problem.  (That `testProxy` test failed towards an old DAViCal server)

**Comment by tobixen** [comment]
I've tried to work around this by leaving the variable `url` as an object, and rather put in `str(url)` where it may be needed - though I'll wait until tomorrow pushing it.

**Comment by tobixen** [comment]
Tests pass, and I consider this issue to be fixed.

**Comment by neelusR** [comment]
Thanks for the fix. I verified and it works for me. Sorry I did not have time to make a pull request, but I see your fix is much more structural than mine would have been.
