### ISSUE TITLE
date_search with datetime.now() is returning events in the past

### ISSUE THREAD

**Issue by jakeprice-dev** [python-caldav/caldav#207]
Hello, I'm working on a script to notify me one hour before an event is due to occur, via Telegram.

However, I'm having some issues using `date_search`. It fetches events within the next hour (and no further), but it also seems to be returning events on the specified day that have already occurred (including all day events which in Fastmail at least "start" at 00:00).

Here's the example's I'm working with today (screenshot from my Fastmail calendar).

![Screenshot from 2022-08-14 21-04-20](https://user-images.githubusercontent.com/88721839/184553068-4760fb25-4354-4c43-b0f6-917c35bc5da6.png)

Here's the code I'm using to search for events.

```python
    with caldav.DAVClient(url=url, username=username, password=password) as client:

        # Fetch calendar
        cal = client.principal().calendar(name=calendarid)

        events = cal.date_search(
            start=datetime.datetime.now(),
            end=datetime.datetime.now() + datetime.timedelta(hours=1),
            expand=True,
        )

        for event in events:
            e = event.instance.vevent
            item_date = e.dtstart.value.strftime("%Y-%m-%d %H:%M")
            item_summary = e.summary.value
            item = f"{item_date} {item_summary}"
            print(item)
```

This is what it's returning at 20:47 tonight. You can see the two events in the past.

```text
Upcoming Event
2022-08-14 00:00 Test 1 All Day
2022-08-14 20:00 Upcoming Test
2022-08-14 21:00 Upcoming Test 2
```

Any ideas what might be going on?

**Comment by tobixen** [comment]
Hm ... not sure if this covers anything, but ...

* According to the RFC, the date search should return events where any part of the event matches the timespan in the search.  So if the event starts at 20:00 and ends on 23:00, a date search from 22:00 will find it.
* Similarly, full day events should show up, even if the event has already started
* And then there are the recurring events.  Those are a bit difficult, very few servers supports the standard to the letter.
* It could also be a timezone issue.

Due to the first one, I believe you will in any case need to filter the events on the client side ... and if you need to do any filtering on the client side, then probably it doesn't matter much if the date search returns any extra events.  It's worse if too few events are passed ... i.e. if it's a timezone issue.

**Comment by jakeprice-dev** [comment]
Thanks for the quick reply @tobixen that makes perfect sense and would explain the behavior I'm seeing.

Will do some filtering on my side.
