### ISSUE TITLE
Radicale uses nonstandard URLs

### ISSUE THREAD

**Issue by BeatLink** [python-caldav/caldav#226]
It appears that Radicale is using non standard urls to host caldav files. 

On normal caldav servers, (nextcloud, etc), the caldav file can be found at the following location

example.com/user/03898134-59a0-11ed-a6d7-cb4c1cf0d9f0

but under radicale it can be found at 

example.com/user/tasks-03898134-59a0-11ed-a6d7-cb4c1cf0d9f0 (notice the tasks- bit)

or example.com/user/calendars-03898134-59a0-11ed-a6d7-cb4c1cf0d9f0 (notice the calendars- bit)

When creating a calendar on a radicale server using python-caldav, the url of the generated calendar does not reflect radicale's actual url format and that results in 404 errors when trying to modify the calendar.

**Comment by tobixen** [comment]
I'm a bit confused on this one.  Radicale is one of the two calendar servers that I'm testing frequently against, so at least all the test code passes.  If you have any troubles with radicale, then I encourage you to write up some specific code that fails.

The caldav standard puts no constraint on the file name of the event/task/journal, but it should be a direct child of the calendar if I've understood it correct.  So if the calendar URL is `example.com/user/`, then both `example.com/user/calendars-03898134-59a0-11ed-a6d7-cb4c1cf0d9f0.ics` and `example.com/user/03898134-59a0-11ed-a6d7-cb4c1cf0d9f0.ics` should be valid URLs.  There need not be any correlation between the URL/filename and the UID of the event, but the caldav library will use the uid as the filename for new events.  For a new event with UID 03898134-59a0-11ed-a6d7-cb4c1cf0d9f0, the caldav client library will use `example.com/user/03898134-59a0-11ed-a6d7-cb4c1cf0d9f0.ics` as the URL.  It's a while since last time I read the RFC, but I believe the calendar server may rename the file and return a 301 or 302 redirect.  The caldav client library will honor such a redirect.

The caldav standard also does not put many restrictions on the UID.  Both 03898134-59a0-11ed-a6d7-cb4c1cf0d9f0 and tasks-03898134-59a0-11ed-a6d7-cb4c1cf0d9f0 are valid UIDs.  The caldav standard encourages the usage of timestamp, serial number and domain in the UID - like `20010712T182145Z-123401@example.com`.  At some point I decided to use uuids rather than the format above when generating UIDs, perhaps I didn't read the above well enough.

**Comment by tobixen** [comment]
Thanks, I'll have a look into it when I get time.

The `children` method is one out of several ways to get things out of the calendar.  Dependent on how well the server supports the standards, some methods may work on some servers and others not.  Instead of `calendar.children()` it's also possible to try to use `calendar.objects()` or one or more of those: `calendar.events()` ,`calendar.todos()`, `calendar.journals()`.  Even `calendar.search()` may be used.  It's a bit messy, I intend to make a more tidy interface in 1.0, as well as ways of discovering or configuring compatibility problems and working around those.

When `calendar.children()` works for all calendars except those that are created through the library, this sounds like a problem at the library side, not the server side.  I will try to copy your code above into the testing framework and take it from there.

I'm quite busy this week and probably into the next one as well, not sure when I will find a time slot for this.

**Comment by BeatLink** [comment]
Right, all those methods fail with the above error. In fact, any method that attempts to draw data from the server results in that 404 error because the URL that pycaldav sets when creating the calendar is not the URL that one would receive from running principal.calendars()

pycaldav when creating the calendar sets the calendar.url to something like this

example.com/user/03898134-59a0-11ed-a6d7-cb4c1cf0d9f0

but the url of the calendar that *actually* gets created on the radicale server looks like this 

example.com/user/tasks-03898134-59a0-11ed-a6d7-cb4c1cf0d9f0 

with either tasks- or calendar- preceeding the ID, depending on the type of object that was created. 

pycaldav is attempting to access the server with the wrong URL resulting in the 404 not found errors.

**Comment by tobixen** [comment]
Cool.  I'll ensure we have tests and a fix in the upcoming 0.10.1-release.

**Comment by tobixen** [comment]
I'm not able to reproduce.  What version of Radicale do you use?

**Comment by BeatLink** [comment]
3.1.8 (from PyPI)

**Comment by tobixen** [comment]
Still not able to reproduce.

Can you try to download the file I just made - https://github.com/python-caldav/caldav/blob/ece0d29adb762ee381368214ccc5115ada1ece45/tests/tmp_226.py - and see if it does the same in your environment as mine?

**Comment by BeatLink** [comment]
Your script works but the problem still occurs with my radicale install. The only difference i can determine is that radicale is being run from within python in your script's case while in my script's case its a seperate process

**Comment by tobixen** [comment]
I'm also not able to reproduce when starting up radicale as a separate process

**Comment by tobixen** [comment]
Perhaps you have some site-local configuration causing this behaviour?  Anyway, looking into `radicale/app/mkcalendar.py` in the radicale project, I don't see any code prepending the calendar path in any way.

I can see one potential bug in the current client side code - it will ignore a 301/302 redirect from the server side - it should probably be picked up and interpreted as the correct location for the calendar.  Perhaps fixing this would solve your problem ... but I would be sort of working blindfolded if I was to implement anything like that.  I would probably either need access to run the test code towards your server, or you would have to do the work yourself.  It's in `caldav/object.py`, `class Calendar`, `def _create`, after `r = self._query` there should be a check for `r.status`, and if it's 301/302, then `self.url` needs to be changed.

**Comment by BeatLink** [comment]
Here's my config file:

```
[storage]
type = radicale_storage_decsync
filesystem_folder = <path to filesystem folder>
decsync_dir = <path to decsync dir>

[auth]
type = htpasswd
htpasswd_filename = <path to password file>
# encryption method used in the htpasswd file
htpasswd_encryption = md5

[server]
hosts = 0.0.0.0:5232, [::]:5232
```

**Comment by BeatLink** [comment]
Do you have the caldav/object.py folder with the changes i could test?

**Comment by tobixen** [comment]
> [storage]
> type = radicale_storage_decsync

From the config file template, the valid options here are `multifilesystem` and `multfilesystem_nolock`.  While I find lots of references in the code for `multifilesystem`, I find no references for `radicale_storage_decsync`.  However, I do find some references to radicale_storage_decsync using a popular search engine ... https://github.com/39aldo39/Radicale-DecSync ... I think that this is not a part of Radicale.  I guess that this is the reason why the calendar URL changes after saving it.

**Comment by BeatLink** [comment]
It appears that the radicale storage is indeed the cause of the issue. Closing ticket.
