### ISSUE TITLE
Feature Request: Include IDs in principal().calendars()

### ISSUE THREAD

**Issue by BeatLink** [python-caldav/caldav#227]
With the varying URL formats that each caldav server has, a more reliable way of accessing calendars could be by their UIDs, In that respect, I'm requesting the ability for the principal.calendars function to include the ids of the calendars in its output (perhaps by parsing the url).

If this feature is implemented then searching for a particular calendar via its ID could be as easy as the following

`next(calendar for calendar in client.principal().calendars() if calendar.id == id)`

**Comment by tobixen** [comment]
I have been a bit confused myself (I didn't first read the standards and then write up the caldav library - I found the existing caldav library in a hope that I wouldn't have to read the standards, found that the library didn't work out well enough, tried to hammer on it until it was working for my use cases, and eventually ended up with the maintainer hat).

It's a while since last time I read through the standards, but as far as I remember ...

* A CalDAV calendar does not have a UID or an ID.  It is uniquely identified only by it's URL (an event may be copied across distinct servers and hence needs a globally unique UID, but there is no such need for a calendar).
* A CalDAV calendar may have a "display name" property.  It's possible to read it and set it through the caldav library.
* The caldav client library has the concepts of `id` and `name`.  (I will create a new API in version 1.0, and it will have no references to `name`, only `display_name`).  cal_id is understood to be the last part of the URL.
* `Principal.calendar()` and `CalendarSet.calendar()` takes two parameters, `name` and `cal_id`.  In `cal_id` it's possible to pass either a full URL, the path to the calendar or just the last part of the URL.  If `name` is passed and no `cal_id` is passed, the server will look up the calendar by name.

Hence, if I'm understanding you correct, the code already does what you want.  Just use `Principal.calendar()` instead of `Principal.calendars()`.
