### ISSUE TITLE
Does not exists release pipeline 

### ISSUE THREAD

**Issue by ArtemIsmagilov** [python-caldav/caldav#413]
This CD automatically push releases on pypi

**Comment by tobixen** [comment]
Automatic releases are not going to happen, at least not in the near future.  I have a long check-list I'm running through for every release.

* I need to run the tests "manually" towards a lot of different calendar servers.  I don't feel confident pushing the passwords and usernames to some external CI/CD-service.  There is _always_ something breaking, and tedious work to check up if it's due to changes on the server side or changes on the client side.
* I also spend some time and efforts writing some release notes and making sure the changelog is in sync
* Prior to a release, it's also nice to verify that the documentation is up-to-date and look through the issue tracker.
