### ISSUE TITLE
sorting search using dtstart not working

### ISSUE THREAD

**Issue by dusscloud** [python-caldav/caldav#448]
I have a nextcloud caldav  server on which i want to get some events within the next 30 days and have them sorted by dtstart.
I succeed to get the events, but they are not sorted at all.

Here my code sample

    end_search=datetime.now() + timedelta(days=30)
    today = datetime.now().date()
    events_fetched = calendar.search(
        sort_keys=("dtstart"),
        comp_class=caldav.Event,
        start=today,
        end=end_search,
        expand=True,
    )
    if len(events_fetched) > 0 :
        for event in events_fetched : print (event.instance.vevent.dtstart.value)

Result: 

2024-11-10 17:00:00+00:00
2024-11-14 21:00:00+00:00
2024-11-09 19:00:00+00:00

I tried with   sort_keys=("dtstart") or  sort_keys=("DTSTART"), same result

I am using debian with python3-caldav package (currently 0.11.0-1)

**Comment by tobixen** [comment]
Thiis should work indeed, but 0.11.0-1 is a very old version.  Try 0.14 instead.

**Comment by dusscloud** [comment]
I tested on another machine (ubuntu) with python3-caldav 1.3.9-1
Same result :(

**Comment by tobixen** [comment]
We do have test code for this, so it's weird - but I will look more into it.

**Comment by tobixen** [comment]
Ah, I reproduced and understood the problem.

`sort_keys` are supposed to be a list or a sequence.  In python, a sequence can be written as `(a,b,c)`.  However, `(a)` is not a sequence, it's merely an expression encapsulated in parenthesis.  A sequence with one element can be written as `(a,)`.  So, `("dtstart")` is the equivalent of the list `("d", "t", "s", "t", "a", "r", "t")` which doesn't make sense, hence the output is not sorted in any sensible order. 

Write `sort_keys=("dtstart",),` and it should work.

I'm considering to write some safeguards here that a string will be handled as one sort key rather than a sequence of characters.

**Comment by dusscloud** [comment]
it works indeed ! thanks a lot

**Comment by tobixen** [comment]
Sorry the noise.  In the master version, it should work to just do `sort_keys=("DTSTART")`.
