### ISSUE TITLE
Calendar.date_search ignores dates given

### ISSUE THREAD

**Issue by Achimh3011** [python-caldav/caldav#52]
dates passed into `Calendar.date_search`are supposed to get their timezones fixed if pytz timezones are employed. However, the second return statement (taking care of non-pytz case) is incorrectly indented, making the functione return `None` and thus removing the date filter.

**Comment by BearWithTie** [comment]
Sorry for reviving this, but I stumbled across this because I recently updated from 0.5.0 which didn't have `_fix_tz`. The problem is that currently it's not possible to use `datetime.date` objects in `date_search` (which worked in 0.5.0), despite the comment saying 

> if the dt object is a date, do nothing.

The error is as follows as we try to replace the timezone on a `datetime.date` which doesn't have one.

> Traceback (most recent call last):
>   [...]
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\caldav\objects.py", line 566, in date_search
>     start = _fix_tz(start)
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\caldav\objects.py", line 40, in _fix_tz
>     return dt.replace(tzinfo=tzlocal.get_localzone())
> TypeError: 'tzinfo' is an invalid keyword argument for replace()

I'm anyway puzzled with the line `return dt.replace(tzinfo=tzlocal.get_localzone())` which is called either if we don't have a `tzname` attribute in which case it doesn't make sense as above error occurs, or if the `datetime` object already has a timezone set, in which case we replace it by the local timezone. Is there any reason for this behavior? Otherwise it could just be changed to `return dt`.

**Comment by tobixen** [comment]
So, I did a bad job reviewing this pull request, it does indeed break the "if dt object is a date, do nothing"-logic.  I need to write more test code and I need to actually run the tests ... but I also have thousands other things to do and the first one on my list now is to sleep.

I find it really embarrassing, but it seems like we'll have to roll a 0.6.2 real soon now.

**Comment by tobixen** [comment]
Could you check if that commit fixes things for you?

**Comment by BearWithTie** [comment]
Works. I think you can remove the `import pytz`, since you're not using it anymore in that file.
