### ISSUE TITLE
calendar.add_event can update as well

### ISSUE THREAD

**Issue by dz0** [python-caldav/caldav#71]
PUT implies update if uid are same -- so maybe would be sensible to rename `add_<obj>` to `save_<obj>`?

**Comment by tobixen** [comment]
I'm against any changes breaking backward compatibility

**Comment by dz0** [comment]
So, maybe just docstring note?

2019-08-14, tr 12:25, Tobias Brox <notifications@github.com> rašė:

**Comment by tobixen** [comment]
Maybe the method can be renamed, but a "deprecated" alias can be preserved for backward-compatibility?

**Comment by tobixen** [comment]
I've thought a bit on it, and decided to:

* Rename the add_* to save_*, with aliases for backwards compatibility.  The aliases may be removed when 1.0 is released
* Add an attribute "no_overwrite" to the save_*-methods, defaults to False.  If it's True, we'll do a lookup for any existing calendar item with the same uid, and raise an error if it already exists.
* Add an attribute "no_create" to the save_*-methods, defaults to False.  If it's True, we'll do a lookup for any existing calendar item with the same uid, and raise an error if it doesn't already exist.
* Also, raise an error if both no_create and no_overwrite is set to True, as this combination is invalid.

Requires some test code as well ... probably won't get around to fix this today.

**Comment by tobixen** [comment]
I decided to skip the point "raise an error if both no_create and no_overwrite is set to True, as this combination is invalid".  It will pass if no object is given, and otherwise anyway give an error message.  I should exercise it in the tests though ...

**Comment by tobixen** [comment]
We still have those aliases in the code:

```
    add_object = save_object
    add_event = save_event
    add_todo = save_todo
    add_journal = save_journal
```

... but `save_foo` is the "canonical" form, and I've been using it consistently in tests and examples.  In test, doc and examples almost always it's used for adding new stuff to a calendar.  The only exception is some few tests that are explicitly testing the possibilities for changing an old event.

If we want to save changes to an object, the "proper" way to do it is by first searching for the old object, edit it and then use `event.save()`.  

Due to those two things, I'm not really feeling comfortable with this change.  For a method that is used to add stuff to the calendar, `add_event` seems more appropriate to me than `save_event`.  So I'm considering to reverse this change before releasing 3.0 now - make `add_event` the official method for adding events to a calendar, and `save_event` to a deprecated method (which will stay with us for a long time to come - I will consider to add deprecation warnings in caldav v4.0.

There is another dimension here, are those methods at all suitable for editing events?  An event on a caldav calendar effectively have two IDs, it's the URL and it's the UID.  The URL is decided by the client on first save.  This library has a deterministic way of rewriting UIDs into URLs, so if saving an event with the same UID several times in a row, it will always be overwritten.  However, other clients may do things differently - so if the event was already added to the server by some other client and we afterwards try to overwrite it using the `save_event` method. using the same UID in the object, but putting to a different URL ... what happens then?  (and what should happen according to the RFC?).

I will consider to do some research on this.  Anyway,  perhaps I shouldn't overthink this too much, after all `save` is indeed used i.e. in editors to add a new file to the file system.  And even though it's not quite "pythonic" to have more than one way to do things, I do like a bit that end-users may choose what they feel more comfortable with.

**Comment by tobixen** [comment]
Saving an object with the same UID but different URL will cause an error to be raised at most servers - while others (in breach of RFC 5545 and RFC 4791 section 4.1) will create a duplicate object.

My thoughts on this:

* I think it makes sense to revert and let `add_object` be the canonical method name, because this method is really meant for adding not updating events.
* Maybe, possibly, we should check if the UID exists in the calendar and then change the URL if needed.  But I think not.

**Comment by tobixen** [comment]
So I've made up my mind on this.  I will revert back to the pre-2020-behaviour.  Those methods should be named `add_object` etc.  For the sync interface we still need to support `save_object` for the foreseeable future.  Examples and doc should be clear that those methods are meant for adding content.  While it's possible to update an object by keeping the same UID and URL but posting different data, the correct way of updating objects is to do `my_event_object.save()`.

I will not bother adding complexity to make sure that `calendar.save_event(data)` will actually update an existing object.  The correct way of doing this would be something like this:

```
uid = exctract_uid_from_ical(new_data)
obj = calendar.object_by_uid(uid)
obj.data = new_data
 obj.save()
```

Admittedly, more lines, but I believe this is a rather rare corner case.

`object_by_uid` should be renamed to `get_object_by_uid`.
