### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 224: ordinal not in range(128)

### ISSUE THREAD

**Issue by storyjesse** [python-caldav/caldav#83]
The following errors appear to be caused by davclient trying to pass data in unicode to a caldav server that only accepts ascii or am I completely wrong??

```
  File "../calendar-cli/calendar-cli.py", line 172, in _calendar_addics
    c.add_event(ics)
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.6.2-py2.7.egg/caldav/objects.py", line 513, in add_event
    return Event(self.client, data=ical, parent=self).save()
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.6.2-py2.7.egg/caldav/objects.py", line 962, in save
    self._create(self._data, self.id, path)
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.6.2-py2.7.egg/caldav/objects.py", line 934, in _create
    {"Content-Type": 'text/calendar; charset="utf-8"'})
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.6.2-py2.7.egg/caldav/davclient.py", line 197, in put
    return self.request(url, "PUT", body, headers)
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.6.2-py2.7.egg/caldav/davclient.py", line 228, in request
    .format(method, url, combined_headers, body))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 224: ordinal not in range(128)

```

**Comment by tobixen** [comment]
No, this is not a server side problem, this is a bug on the client side as far as I can see - the bug is even not on the communication part, but in debug logging.  I think it's a general problem with python, it allows mixing of "unicode"-objects and "byte"-objects, but as soon as some non-ascii characters are passed it will fail like that (and to make matters worse, an ordinary string in python2 is a byte-object, while it's a unicode object in python3).

The proper way to fix this is to first try to trigger the problem in a unit test or a functional test and then make the code robust.  The easy workaround you can do is to just remove the "log.debug"-line from davclient.py.  Or, eventually, try running it in python3.

**Comment by tobixen** [comment]
Could I have your ics file?  (or, if it's considered confidential, try editing it to something that fails without revealing any private data - alternatively, if it's not strictly confidential but you still don't want to publish it, send it privately to me, i.e. by email).

**Comment by tobixen** [comment]
This should be fixed in master branch of caldav, or in the next release
